# Generated by Django 6.0.5 on 2026-06-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_user_is_online_conversation_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('buyer', 'seller', 'car')},
        ),
    ]
