# Generated by Django 6.0.5 on 2026-06-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_conversation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='renting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
